"""Change the image db

Revision ID: 8a5d2237b98a
Revises: 3ca130b33c6d
Create Date: 2024-06-17 10:13:53.011279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a5d2237b98a'
down_revision = '3ca130b33c6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_screenshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game_image')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('cover_image')

    op.create_table('game_image',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('image_path', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('game_screenshots')
    # ### end Alembic commands ###
