"""Add type field to Game model

Revision ID: 9e57073bc0d0
Revises: f9404b8bae39
Create Date: 2024-06-09 00:47:03.697026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e57073bc0d0'
down_revision = 'f9404b8bae39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_game')
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.String(length=255), nullable=True))
        batch_op.alter_column('release_date',
               existing_type=sa.TEXT(),
               type_=sa.Date(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.alter_column('release_date',
               existing_type=sa.Date(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('type')

    op.create_table('_alembic_tmp_game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('release_date', sa.DATE(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('is_discounted', sa.BOOLEAN(), nullable=True),
    sa.Column('discount_price', sa.FLOAT(), nullable=True),
    sa.Column('tags', sa.VARCHAR(length=255), nullable=True),
    sa.Column('developer', sa.VARCHAR(length=256), nullable=True),
    sa.Column('publisher', sa.VARCHAR(length=256), nullable=True),
    sa.Column('type', sa.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
