"""Add new_field to Game model

Revision ID: f9404b8bae39
Revises: 0aa12754ae25
Create Date: 2024-01-01 21:50:39.578863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9404b8bae39'
down_revision = '0aa12754ae25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('developer', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('publisher', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_column('publisher')
        batch_op.drop_column('developer')

    # ### end Alembic commands ###
